//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSPortal3.PortalAdministration.userInterfaces.moduleCRM.crmDailyOpportunity {
    
    
    public partial class pageDailyOpportunityDetail {
        
        /// <summary>
        /// controlActivity control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SBSPortal3.PortalAdministration.userInterfaces.moduleSystem.crmActivityPlugin.controlActivity controlActivity;
        
        /// <summary>
        /// ControlAttachment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SBSPortal3.PortalAdministration.userInterfaces.moduleSystem.systemAttachment.ControlAttachment ControlAttachment;
        
        /// <summary>
        /// controlComment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SBSPortal3.PortalAdministration.userInterfaces.moduleSystem.systemComment.controlComment controlComment;
    }
}
